# Generated by Django 2.2.6 on 2020-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете прикрепить сюда фотографию!', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
