# Generated by Django 2.2.6 on 2020-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете прикрепить сюда фотографию', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
